-- Round Unit_Price to 2 decimal places.
-- select ROUND(unit_price, 2) from orders;
-- Find total sales per order.
-- select order_id,sum(unit_price * quantity) AS total_sales from orders group by order_id;
-- Calculate average order value.
-- select avg(order_total) AS avg_order_value
-- from (
--     select order_id,
--            SUM(unit_price * quantity) AS order_total
--     from orders
--     group by order_id
-- ) order_totals;
-- Find highest product price.
-- select unit_price, MAX(unit_price) AS highest_price FROM orders;
-- Find lowest product price.
-- select unit_price, mjn(unit_price) AS lowest_price FROM orders;
-- Calculate percentage discount applied.
-- select * from orders;
-- SELECT order_id,unit_price,discounted_price,
-- ((unit_price - discounted_price) / unit_price) * 100 AS discount_percentage
-- from orders;
-- Find modulus of Quantity divided by 2.
-- select QUANTITY%2 from orders; 
-- SELECT Quantity, MOD(Quantity, 2) AS quantity_modulus FROM orders;
-- Convert negative values to positive.
-- SELECT order_id,Quantity, ABS(Quantity) AS converted_value
-- FROM orders;
-- SELECT order_id,UNIT_PRICE,TRUNC(UNIT_PRICE, 2) AS truncated_price from orders;
-- Calculate power of 2^5.
-- select power(2,5) ;
-- Find absolute difference between two prices.
-- select unit_price, ABS(unit_price_old - unit_price_new) AS price_difference from ORDERS;
-- Find random number between 1 and 100
-- select trunc(DBMS_RANDOM.VALUE(1, 101)) AS random_number FROM dual;
-- Divide total sales by number of orders
-- select sum(sales_amount) / count(order_id) AS avg_sales_per_order from orders;
-- Find ceiling value of price.
-- SELECT CEIL(unit_price) AS ceiling_price from orders;
-- Find floor value of price.
-- select FLOOR(unit_price) AS floor_price from orders;
-- Convert decimal to integer.
-- Select trunc(unit_price) AS integer_price from orders;
-- Calculate compound interest
-- select principal,
--        power((1 + rate/compounds_per_year), compounds_per_year * years) * principal AS compound_amount
-- from investments;