-- Write a query to convert all customer names to uppercase.
-- SELECT UPPER(Customer_Name) AS uppercase_name
-- FROM Orders;
-- Extract the first 5 characters from Product_Name.
-- SELECT SUBSTR(Product_Name, 1, 5) AS first_five_chars
-- FROM Orders;
-- Find the length of each Customer_Name.
-- SELECT Customer_Name, LENGTH(Customer_Name) AS name_length
-- FROM Orders;
-- Replace the word "Rice" with "Premium Rice" in Product_Name.
-- SELECT REPLACE(Product_Name, 'Rice', 'Premium Rice') AS updated_product
-- FROM Orders;
-- Remove leading and trailing spaces from Customer_Name.
-- SELECT TRIM(Customer_Name) AS cleaned_name
-- FROM Orders;
-- Concatenate First_Name and Last_Name as Full_Name.
-- SELECT First_Name || ' ' || Last_Name AS Full_Name
-- FROM Customers;
-- Find customers whose names start with 'A'.
-- SELECT Customer_Name
-- FROM Orders
-- WHERE Customer_Name LIKE 'A%';
-- Extract the domain name from Email_ID.
-- Find the position of '@' in Email_ID.
-- Reverse the Product_Name.
-- SELECT REVERSE(Product_Name) AS reversed_name
-- FROM Orders;
-- Convert the first letter of each word in Product_Name to uppercase.
-- SELECT INITCAP(Product_Name) AS proper_case_name
-- FROM Orders;
-- Extract the last 3 characters from Order_ID.
-- SELECT SUBSTR(Order_ID, -3) AS last_three
-- FROM Orders;
-- Count how many times letter 'a' appears in Customer_Name.
-- SELECT Customer_Name,
--        LENGTH(Customer_Name) - LENGTH(REPLACE(LOWER(Customer_Name), 'a', '')) AS a_count
-- FROM Orders;
-- Mask the last 4 digits of a phone number.
-- SELECT RPAD(SUBSTR(Phone_Number, 1, LENGTH(Phone_Number) - 4), LENGTH(Phone_Number), '*') AS masked_phone
-- FROM Customers;
-- Split Full_Name into First_Name and Last_Name.
-- SELECT SUBSTR(Full_Name, 1, INSTR(Full_Name, ' ') - 1) AS First_Name,
--        SUBSTR(Full_Name, INSTR(Full_Name, ' ') + 1) AS Last_Name
-- FROM Customers;
-- Compare two columns ignoring case sensitivity.
-- SELECT *
-- FROM Orders
-- WHERE UPPER(Column1) = UPPER(Column2);
-- Find customers whose name contains 'kumar'.
-- SELECT Customer_Name
-- FROM Orders
-- WHERE LOWER(Customer_Name) LIKE '%kumar%';
-- Pad Order_ID with leading zeros to make it 6 digits.
-- SELECT LPAD(Order_ID, 6, '0') AS padded_order_id
-- FROM Orders;
-- Extract substring between two characters.
-- Extract the domain name from Email_ID.
-- Find the position of '@' in Email_ID.
-- Remove all special characters from Product_Code.